services:
  mariadb:           
    container_name: mariadb
    image : mariadb:inception
    build: ./requirements/mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build: ./requirements/wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
  nginx:
    container_name: nginx
    image : nginx:inception
    build: ./requirements/nginx/.
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  database:
    name: database
    driver_opts:
      type: none
      o: bind
      device: /home/ibenaait/data/database
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/ibenaait/data/wordpress

networks:
  inception:
    name: inception